---
- hosts: webserver
  remote_user: test1000
  become: yes
  tasks:
      - name: Install httpd package
        command: yum install httpd -y
      - name: copy index.html
        shell: echo "This from CommandLine" > /var/www/html/index.html
      - name: start httpd service
        script: ./test1.sh
      - name: start httpd service
        raw: systemctl start httpd
