---
- hosts: server2
  remote_user: test1000
  become: yes
  vars:
    pkg: httpd
  vars_files:
      - abl.yml
      - abl2.yml
          
  tasks:
      - name: Install {{pkg1}} package
        yum: name={{pkg1}} state=installed
      - name: Install {{pkg2}} package
        yum: name={{pkg2}} state=installed
      - name: copy index.html
        copy: src=index.html dest=/var/www/html
        #notify: restart httpd
      - name: start httpd service
        service: name=httpd state=started
      # handles:
      #- name: restart httpd
       # service: name=httpd state=restarted
