---
- hosts: server2
  remote_user: test1000
  become: yes
  tasks:
      - name: Loop item and install
        yum: name={{item}} state=installed
        with_items:
           - httpd
           - curl
           - telnet
