---
- hosts: server2
  remote_user: test1000
  become: yes
  vars_files:
      - check.yml
  tasks:
      - name: Install httpd 
        yum: name=httpd state=installed
        when: {{check}} == "true"
      - name: Install Appachi package
        apt: name=apache2 state=installed
        when: {{check}} == "false"
      - name: start httpd service
        service: name=httpd state=started
